# Databricks notebook source
# MAGIC %md
# MAGIC # Meridian Insights — AI Abstract Enrichment
# MAGIC
# MAGIC Demonstrates **`ai_query()`** to enrich synthetic article abstracts with
# MAGIC realistic, semantically meaningful content generated by the Foundation
# MAGIC Model API. This powers the Vector Search index behind Research Q&A.
# MAGIC
# MAGIC **Cost note:** Uses the 8B instruct model (~10x cheaper than 70B).
# MAGIC 5,000 articles × 80-word abstracts ≈ $0.05 total.

# COMMAND ----------

dbutils.widgets.text("catalog_name", "serverless_stable_k2zkdm_catalog")
dbutils.widgets.text("llm_endpoint", "databricks-meta-llama-3-1-8b-instruct")

catalog = dbutils.widgets.get("catalog_name")
llm = dbutils.widgets.get("llm_endpoint")

import re
if not re.match(r"^[a-zA-Z0-9_-]+$", llm):
    raise ValueError(f"Invalid llm_endpoint name: {llm}")

VS_SOURCE = f"{catalog}.meridian_research.articles_vs_source"
TEMP_TABLE = f"{catalog}.meridian_research._abstract_enrichment_temp"

print(f"Catalog:    {catalog}")
print(f"Model:      {llm}")
print(f"Source:     {VS_SOURCE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Load all articles for enrichment

# COMMAND ----------

from pyspark.sql import functions as F

if not spark.catalog.tableExists(VS_SOURCE):
    raise RuntimeError(f"Table {VS_SOURCE} does not exist. Run 09_vs_sync.py first.")

candidates = spark.table(VS_SOURCE)
total = candidates.count()
print(f"Enriching all {total} articles across publication types:")
candidates.groupBy("publication_type").count().orderBy("count", ascending=False).show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Before — sample of synthetic abstracts (Faker-generated)

# COMMAND ----------

candidates.select("title", F.substring("abstract", 1, 120).alias("abstract_preview")).show(5, truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Generate realistic abstracts with `ai_query()`
# MAGIC
# MAGIC Each call asks the Foundation Model to produce a structured abstract
# MAGIC (BACKGROUND / METHODS / RESULTS / CONCLUSIONS) from the article title.
# MAGIC The title already contains real biomedical terms — drugs, genes,
# MAGIC diseases, and techniques — so the generated abstracts are semantically
# MAGIC rich and embeddable.

# COMMAND ----------

enriched = candidates.withColumn(
    "abstract",
    F.expr(f"""
        ai_query(
            '{llm}',
            concat(
                'Write a concise 80-word scientific abstract for a biomedical paper titled: ',
                title,
                '. Format: BACKGROUND: (1 sentence) METHODS: (1 sentence with sample size) RESULTS: (1-2 sentences with p-values) CONCLUSIONS: (1 sentence). No preamble.'
            )
        )
    """),
)

enriched.createOrReplaceTempView("enriched_abstracts")
print(f"Generating abstracts for {total} articles via {llm}...")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. After — AI-generated abstracts

# COMMAND ----------

spark.sql("""
    SELECT title, substring(abstract, 1, 200) as abstract_preview
    FROM enriched_abstracts LIMIT 5
""").show(truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Write enriched abstracts to temp table & merge

# COMMAND ----------

spark.sql(f"DROP TABLE IF EXISTS {TEMP_TABLE}")
spark.sql(f"""
    CREATE TABLE {TEMP_TABLE} AS
    SELECT article_id, abstract FROM enriched_abstracts
""")

merge_count = spark.sql(f"SELECT count(*) FROM {TEMP_TABLE}").collect()[0][0]
print(f"Temp table created with {merge_count} enriched abstracts")

# COMMAND ----------

spark.sql(f"""
    MERGE INTO {VS_SOURCE} t
    USING {TEMP_TABLE} s
    ON t.article_id = s.article_id
    WHEN MATCHED THEN UPDATE SET t.abstract = s.abstract
""")
print(f"Merged {merge_count} enriched abstracts into {VS_SOURCE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Trigger Vector Search index sync
# MAGIC
# MAGIC The VS index uses Delta CDF to detect changes. The MERGE created
# MAGIC change records, so a sync will re-embed the updated abstracts.

# COMMAND ----------

from databricks.sdk import WorkspaceClient

VS_INDEX = f"{catalog}.meridian_research.articles_vs_index"
w = WorkspaceClient()

try:
    idx = w.vector_search_indexes.get_index(VS_INDEX)
    if idx.status and idx.status.ready:
        w.vector_search_indexes.sync_index(VS_INDEX)
        print(f"Sync triggered for '{VS_INDEX}'")
        print("The index will re-embed the enriched abstracts in the background.")
    else:
        print(f"Index not ready — sync skipped")
except Exception as e:
    print(f"Index sync failed: {e}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Verify — sample enriched articles from VS source

# COMMAND ----------

spark.sql(f"""
    SELECT title, substring(abstract, 1, 200) as abstract_preview, publication_type
    FROM {VS_SOURCE}
    WHERE length(abstract) > 200
      AND abstract NOT LIKE 'BACKGROUND: %Interview%'
      AND abstract NOT LIKE 'BACKGROUND: %Despite%discussion%'
    ORDER BY RAND()
    LIMIT 10
""").show(truncate=False)
